const state={view:'recipes',query:'',category:'',recipes:[],favorites:[],checkedIngredients:{},deletedPublishedIds:[],recipeWarnings:[],settings:{theme:'light'},currentId:null,cookStep:0,message:'',messageType:'ok'};
let wakeLock=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
const uid=(prefix='r')=>`${prefix}${Date.now()}${Math.floor(Math.random()*100000)}`;
function db(){if(db.p)return db.p;db.p=new Promise((resolve,reject)=>{const req=indexedDB.open('kochbuch',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('kv'))req.result.createObjectStore('kv')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return db.p}
async function idbGet(key){const d=await db();return new Promise((resolve,reject)=>{const req=d.transaction('kv','readonly').objectStore('kv').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function idbSet(key,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('kv','readwrite');tx.objectStore('kv').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function idbDelete(key){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('kv','readwrite');tx.objectStore('kv').delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function recipeValidationErrors(d,{requireId=false}={}){const errors=[];if(!d||typeof d!=='object'||Array.isArray(d))return['Rezept ist kein Objekt'];if(requireId&&(!d.id||typeof d.id!=='string'))errors.push('id fehlt');if(!String(d.titel||d.name||'').trim())errors.push('titel fehlt');if(!String(d.kategorie||'').trim())errors.push('kategorie fehlt');const portions=Number(String(d.portionen??d.recipeYield??'').replace(',','.').match(/\d+(?:\.\d+)?/)?.[0]);if(!Number.isFinite(portions)||portions<=0)errors.push('portionen muss eine positive Zahl enthalten');if(!Array.isArray(d.zutaten)||!d.zutaten.length)errors.push('zutaten fehlen');else d.zutaten.forEach((z,i)=>{if(typeof z==='string'){if(!z.trim())errors.push(`Zutat ${i+1} ist leer`)}else if(!z||typeof z!=='object'||!String(z.name||'').trim())errors.push(`Zutat ${i+1}: name fehlt`)});if(!Array.isArray(d.schritte)||!d.schritte.length)errors.push('schritte fehlen');else d.schritte.forEach((s,i)=>{const action=typeof s==='string'?s:s?.aktion||s?.text;if(!String(action||'').trim())errors.push(`Schritt ${i+1}: aktion fehlt`)});if(d.publishedVersion!==undefined&&(!Number.isInteger(Number(d.publishedVersion))||Number(d.publishedVersion)<1))errors.push('publishedVersion muss mindestens 1 sein');if(d.bild!==undefined&&typeof d.bild!=='string')errors.push('bild muss Text sein');return errors}
function normalizeStep(s){if(typeof s==='string')return{titel:'',aktion:s,startwert:'',tipp:''};return{titel:String(s?.titel||''),aktion:String(s?.aktion||s?.text||''),startwert:String(s?.startwert||''),tipp:String(s?.tipp||s?.tip||'')}}
function normalizeRecipe(d,preserveId=true){const steps=Array.isArray(d.schritte)?d.schritte:[];return{id:preserveId&&d.id?String(d.id):uid(),titel:String(d.titel||d.name||'Unbenannt'),kategorie:String(d.kategorie||'Sonstiges'),schwierigkeit:String(d.schwierigkeit||''),portionen:d.portionen??d.recipeYield??'',zeitGesamt:String(d.zeitGesamt||d.zeit||d.totalTime||''),einleitung:String(d.einleitung||d.beschreibung||d.description||''),bild:String(d.bild||d.image||''),quelle:String(d.quelle||d.source||d.url||''),quelleName:String(d.quelleName||d.sourceName||''),werkzeuge:Array.isArray(d.werkzeuge)?d.werkzeuge:[],zutaten:Array.isArray(d.zutaten)?d.zutaten:[],schritte:steps.map(normalizeStep),tipps:Array.isArray(d.tipps)?d.tipps:[],publishedVersion:Number(d.publishedVersion||1)}}
function mergePublishedRecipes(stored,deletedIds=[]){const local=(Array.isArray(stored)?stored:[]).map(r=>normalizeRecipe(r,true));const deleted=new Set(Array.isArray(deletedIds)?deletedIds:[]);state.recipeWarnings=[];for(const raw of DEFAULT_RECIPES){const errors=recipeValidationErrors(raw,{requireId:true});if(errors.length){state.recipeWarnings.push(`${raw?.titel||raw?.id||'Unbekanntes Rezept'}: ${errors.join(', ')}`);continue}const published=normalizeRecipe(raw,true);if(deleted.has(published.id))continue;const idx=local.findIndex(r=>r.id===published.id||(published.quelle&&r.quelle===published.quelle)||(norm(r.titel)===norm(published.titel)&&r.kategorie===published.kategorie));if(idx<0){local.push(published);continue}const current=local[idx];if((published.publishedVersion||1)>(current.publishedVersion||1)){const ownImage=String(current.bild||'').startsWith('data:')?current.bild:'';local[idx]={...published,bild:ownImage||published.bild}}}return local}
async function init(){let recipes,favorites,checked,settings,deletedIds;try{[recipes,favorites,checked,settings,deletedIds]=await Promise.all([idbGet('recipes'),idbGet('favorites'),idbGet('checkedIngredients'),idbGet('settings'),idbGet('deletedPublishedIds')])}catch(e){}if(!Array.isArray(recipes)||!recipes.length){try{const old=localStorage.getItem('kochbuch.recipes');if(old)recipes=JSON.parse(old)}catch(e){}}if(!checked){try{checked=JSON.parse(localStorage.getItem('kochbuch.opt')||'{}')}catch(e){}}if(!settings){settings={theme:localStorage.getItem('kochbuch.theme')||'light'}}state.deletedPublishedIds=Array.isArray(deletedIds)?deletedIds:[];state.recipes=mergePublishedRecipes(recipes,state.deletedPublishedIds);state.favorites=Array.isArray(favorites)?favorites:[];state.checkedIngredients=checked&&typeof checked==='object'?checked:{};state.settings=settings&&typeof settings==='object'?settings:{theme:'light'};applyTheme(state.settings.theme||'light',false);await Promise.all([saveAll(),idbDelete('shopping')]);render();if(state.recipeWarnings.length)console.warn('Nicht übernommene Rezepte:',state.recipeWarnings)}
async function saveAll(){await Promise.all([idbSet('recipes',state.recipes),idbSet('favorites',state.favorites),idbSet('checkedIngredients',state.checkedIngredients),idbSet('deletedPublishedIds',state.deletedPublishedIds),idbSet('settings',state.settings)])}
async function saveRecipes(){await idbSet('recipes',state.recipes)}
function applyTheme(theme,persist=true){const t=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=t;state.settings.theme=t;if(persist)idbSet('settings',state.settings).catch(()=>{})}
function toggleTheme(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}
function setView(view){state.view=view;state.currentId=null;state.message='';if(view!=='recipes'&&view!=='favorites')state.query='';window.scrollTo(0,0);render()}
function current(){return state.recipes.find(r=>r.id===state.currentId)}
function toast(message,type='ok'){const el=$('#toast');el.textContent=message;el.className='toast show';el.style.background=type==='err'?'#8f251d':'';clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2600)}
function imgHtml(src,alt){return src?`<img src="${esc(src)}" alt="${esc(alt)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="placeholder" style="display:none">🍽️</div>`:`<div class="placeholder">🍽️</div>`}
function isFavorite(id){return state.favorites.includes(id)}
async function toggleFavorite(id){state.favorites=isFavorite(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];await idbSet('favorites',state.favorites);render();toast(isFavorite(id)?'Zu Favoriten hinzugefügt':'Aus Favoriten entfernt')}
function ingredientText(z){if(typeof z==='string')return z;return[z?.menge,z?.einheit,z?.name].filter(v=>v!==undefined&&v!==null&&String(v).trim()).join(' ')+(z?.hinweis?` · ${z.hinweis}`:'')}
function filteredRecipes(base=state.recipes){const q=norm(state.query);return base.filter(r=>(!state.category||r.kategorie===state.category)&&(!q||norm([r.titel,r.kategorie,...(r.zutaten||[]).map(ingredientText)].join(' ')).includes(q)))}