function recipeCard(r){return`<article class="card"><div class="card-img">${imgHtml(r.bild,r.titel)}<span class="badge">${esc(r.kategorie)}</span><button class="heart ${isFavorite(r.id)?'active':''}" data-favorite="${esc(r.id)}" aria-label="Favorit">${isFavorite(r.id)?'♥':'♡'}</button></div><div class="card-body"><h3>${esc(r.titel)}</h3><div class="meta">${r.schwierigkeit?`<span>${esc(r.schwierigkeit)}</span>`:''}${r.zeitGesamt?`<span>· ${esc(r.zeitGesamt)}</span>`:''}${r.portionen?`<span>· ${esc(r.portionen)} Portionen</span>`:''}</div><p>${esc((r.einleitung||'').slice(0,135))}${(r.einleitung||'').length>135?'…':''}</p><div class="card-actions"><button class="btn primary" data-open="${esc(r.id)}">Öffnen</button></div></div></article>`}
function recipesView(favoritesOnly=false){const categories=[...new Set(state.recipes.map(r=>r.kategorie))].sort((a,b)=>a.localeCompare(b,'de'));const base=favoritesOnly?state.recipes.filter(r=>isFavorite(r.id)):state.recipes;const list=filteredRecipes(base);const title=favoritesOnly?'Favoriten':'Meine Rezepte';return`<section class="hero"><div class="hero-copy"><div class="eyebrow">${favoritesOnly?'Deine Auswahl':'Persönliches Kochbuch'}</div><h1>${title}</h1><p>Durchsuche Titel, Kategorien und Zutaten. Änderungen werden direkt in IndexedDB auf diesem Gerät gespeichert.</p></div><div class="hero-stat"><div class="stat-number">${list.length}</div><div class="stat-label">${favoritesOnly?'gespeicherte Favoriten':'sichtbare Rezepte'}</div></div></section><div class="toolbar"><div class="search"><input id="searchInput" value="${esc(state.query)}" placeholder="Rezepte und Zutaten live durchsuchen"></div><select id="categoryFilter"><option value="">Alle Kategorien</option>${categories.map(c=>`<option ${state.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><button class="btn" data-view="import">➕ Rezept hinzufügen</button></div>${list.length?`<div class="grid">${list.map(recipeCard).join('')}</div>`:`<div class="empty"><h2>Nichts gefunden</h2><p>${favoritesOnly?'Markiere Rezepte mit dem Herz als Favorit.':'Ändere Suche oder Kategorie.'}</p></div>`}`}
function categoriesView(){const counts={};state.recipes.forEach(r=>counts[r.kategorie]=(counts[r.kategorie]||0)+1);const entries=Object.entries(counts).sort((a,b)=>a[0].localeCompare(b[0],'de'));return`<div class="section-title"><div><div class="eyebrow">Übersicht</div><h1>Kategorien</h1><p>Eine Kategorie öffnet sofort die passenden Rezepte.</p></div></div><div class="category-grid">${entries.map(([name,count])=>`<button class="category-card" data-category="${esc(name)}"><strong>${esc(name)}</strong><span>${count} ${count===1?'Rezept':'Rezepte'}</span></button>`).join('')}</div>`}
function aiPrompt(source=''){return`Arbeite direkt in meinem verbundenen GitHub-Repository Maycetin1205/Kochbuch.

Lies zuerst die Datei RECIPE_IMPORT_INSTRUCTIONS.md und befolge sie vollständig. Ich sende dir in diesem Chat ein Rezept und lade das passende Foto hoch.

Deine Aufgabe:
1. Übertrage das Rezept vollständig in das dort beschriebene Rezeptschema.
2. Trage es direkt in default-recipes.js ein oder aktualisiere den vorhandenen Eintrag.
3. Speichere ausschließlich mein hochgeladenes Foto unter images/ in einem geeigneten JPEG- oder WebP-Format. Lade kein fremdes Bild aus dem Internet herunter.
4. Setze den Bildpfad im Rezept auf ./images/<dateiname>.
5. Prüfe die JavaScript-Syntax.
6. Committe die Änderungen direkt auf main.
7. Gib nicht nur JSON oder Beispielcode aus. Führe die GitHub-Änderungen tatsächlich aus.
8. Falls dieser Chat keinen GitHub-Schreibzugriff besitzt, sage das sofort, bevor du das Rezept bearbeitest.

Rezept oder Quelle:
${source||'[Rezepttext oder Link folgt zusammen mit meinem Foto]'}`}
function importView(){return`<div class="section-title"><div><div class="eyebrow">Ein Rezept pro neuem Chat</div><h1>Rezepte hinzufügen</h1><p>Der Knopf kopiert einen festen GitHub-Auftrag und öffnet einen neuen ChatGPT-Chat.</p></div></div><div class="two-col"><section class="panel"><h2>🤖 Direkt über ChatGPT und GitHub</h2><p>Optional Rezepttext oder einen Link einfügen. Danach den neuen Chat öffnen, dort das Rezept sowie dein Foto senden und den kopierten Auftrag einfügen.</p><div class="field"><label for="aiSource">Rezepttext oder Link, falls bereits vorhanden</label><textarea id="aiSource" placeholder="Rezepttext oder https://…"></textarea></div><button class="btn primary" id="openAI" style="margin-top:14px">GitHub-Rezeptchat öffnen</button><div class="install-note"><strong>Der neue Chat soll:</strong> <code>RECIPE_IMPORT_INSTRUCTIONS.md</code> lesen, das Rezept in <code>default-recipes.js</code> eintragen, dein hochgeladenes Foto unter <code>images/</code> speichern und auf <code>main</code> committen. Fremde Bilder werden nicht heruntergeladen.</div></section><section class="panel"><h2>🌐 Nur URL auslesen</h2><p>Die App kann versuchen, strukturierte Rezeptdaten direkt auszulesen. Viele Websites blockieren das. Der GitHub-Rezeptchat ist der zuverlässigere Weg.</p><div class="field"><label for="urlInput">Rezept-URL</label><input id="urlInput" type="url" placeholder="https://…"></div><button class="btn secondary" id="urlImport" style="margin-top:14px">URL importieren</button><div class="hint" style="margin-top:10px">Ohne eigenes Backend funktioniert der direkte URL-Zugriff nicht bei jeder Website.</div></section></div><section class="panel"><h2>Lokales JSON oder Backup</h2><p>Dieses Feld bleibt für lokale Rezepte, Backups oder den Notfall erhalten. Direkt über GitHub hinzugefügte Rezepte erscheinen nach dem Neuladen automatisch in der App.</p><div class="field"><textarea id="jsonArea" placeholder='{"titel":"…","zutaten":[…],"schritte":[…]}'></textarea></div><div class="card-actions" style="margin-top:14px"><label class="btn file-label">JSON-Datei wählen<input id="jsonFile" type="file" accept=".json,application/json,text/plain"></label><button class="btn primary" id="importBtn">Lokal speichern</button><button class="btn" id="exportBtn">Backup exportieren</button></div>${state.message?`<div class="notice ${state.messageType}">${esc(state.message)}</div>`:''}</section>`}
function detailView(){const r=current();if(!r)return recipesView();const checked=state.checkedIngredients[r.id]||{};return`<div class="toolbar"><button class="btn ghost" data-view="recipes">← Rezepte</button></div><section class="detail-head"><div class="detail-photo">${imgHtml(r.bild,r.titel)}</div><div class="detail-info"><div class="eyebrow">${esc(r.kategorie)}</div><h1>${esc(r.titel)}</h1><div class="meta">${[r.schwierigkeit,r.zeitGesamt,r.portionen?`${r.portionen} Portionen`:'' ].filter(Boolean).map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>${r.quelle?`<a class="source-link" href="${esc(r.quelle)}" target="_blank" rel="noopener">↗ ${esc(r.quelleName||'Originalquelle öffnen')}</a>`:''}<p class="intro">${esc(r.einleitung)}</p><div class="card-actions detail-actions"><button class="btn primary" id="startCook">Kochmodus</button><button class="btn" id="detailFavorite">${isFavorite(r.id)?'♥ Favorit':'♡ Favorit'}</button><label class="btn file-label">${r.bild?'Bild ändern':'Eigenes Bild wählen'}<input id="detailImageFile" type="file" accept="image/*"></label>${r.bild?'<button class="btn" id="removeImage">Bild entfernen</button>':''}<button class="btn danger" id="deleteRecipe">Löschen</button></div><div class="hint" style="margin-top:12px">Ein hier ausgewähltes Bild wird komprimiert und nur lokal in IndexedDB gespeichert. Über den GitHub-Rezeptchat hinzugefügte Bilder liegen dagegen dauerhaft im Repository.</div></div></section><section class="recipe-layout"><aside class="ingredients"><h2>Zutaten</h2>${(r.zutaten||[]).map((z,i)=>`<label class="ingredient ${checked[i]?'checked':''}"><input type="checkbox" data-ing="${i}" ${checked[i]?'checked':''}><span>${esc(ingredientText(z))}${z?.optional?' <small>(optional)</small>':''}</span></label>`).join('')||'<p class="hint">Keine Zutaten hinterlegt.</p>'}${r.werkzeuge?.length?`<h3 style="margin-top:24px">Werkzeuge</h3><div class="tools">${r.werkzeuge.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`:''}${r.tipps?.length?`<h3 style="margin-top:24px">Tipps</h3><ul>${r.tipps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</aside><article class="steps"><h2>Zubereitung</h2>${r.schritte.map(stepHtml).join('')}</article></section>`}
function stepHtml(s,i){const signals=Object.entries(s.sinne||{}).filter(([,v])=>v);return`<section class="step"><div><span class="step-num">${i+1}</span><h3>${esc(s.titel||`Schritt ${i+1}`)}</h3></div>${s.startwert?`<div class="meta" style="margin-top:8px"><span class="badge">${esc(s.startwert)}</span></div>`:''}<p class="action">${esc(s.aktion)}</p>${s.zutaten?.length?`<div class="meta">${s.zutaten.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`:''}${signals.length?`<div class="signals">${signals.map(([k,v])=>`<div class="signal"><strong>${esc(SENSE_LABELS[k]||k)}:</strong> ${esc(v)}</div>`).join('')}</div>`:''}${s.fertigWenn?`<div class="truth"><strong>Fertig, wenn:</strong> ${esc(s.fertigWenn)}</div>`:''}${s.warum?`<div class="why"><strong>Warum:</strong> ${esc(s.warum)}</div>`:''}${s.fehler?`<div class="error-box"><strong>Typischer Fehler:</strong> ${esc(s.fehler)}</div>`:''}</section>`}
function cookView(){const r=current();if(!r)return recipesView();const i=Math.max(0,Math.min(r.schritte.length-1,state.cookStep));const s=r.schritte[i];const pct=((i+1)/r.schritte.length)*100;return`<div class="cook-wrap"><div class="toolbar"><button class="btn ghost" id="exitCook">← Rezept</button><span class="badge">Schritt ${i+1} von ${r.schritte.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><article class="cook-card"><div class="eyebrow">${esc(r.titel)}</div><h1>${esc(s.titel||`Schritt ${i+1}`)}</h1>${s.startwert?`<span class="badge">${esc(s.startwert)}</span>`:''}<p class="action" style="font-size:21px;margin-top:22px">${esc(s.aktion)}</p>${s.zutaten?.length?`<div class="tools">${s.zutaten.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`:''}${Object.entries(s.sinne||{}).filter(([,v])=>v).length?`<div class="signals" style="margin-top:20px">${Object.entries(s.sinne||{}).filter(([,v])=>v).map(([k,v])=>`<div class="signal"><strong>${esc(SENSE_LABELS[k]||k)}:</strong> ${esc(v)}</div>`).join('')}</div>`:''}${s.fertigWenn?`<div class="truth"><strong>Entscheidendes Signal:</strong> ${esc(s.fertigWenn)}</div>`:''}${s.fehler?`<div class="error-box"><strong>Achtung:</strong> ${esc(s.fehler)}</div>`:''}<div class="cook-nav"><button class="btn" id="prevStep" ${i===0?'disabled':''}>← Zurück</button><button class="btn primary" id="nextStep">${i===r.schritte.length-1?'Fertig':'Weiter →'}</button></div></article></div>`}
function render(){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const views={recipes:()=>recipesView(false),favorites:()=>recipesView(true),categories:categoriesView,import:importView,detail:detailView,cook:cookView};$('#app').innerHTML=(views[state.view]||views.recipes)();bindView()}