function bindView(){
  const search=$('#searchInput');
  search?.addEventListener('input',e=>{state.query=e.target.value;const pos=e.target.selectionStart;render();const next=$('#searchInput');next?.focus();next?.setSelectionRange(pos,pos)});
  $('#categoryFilter')?.addEventListener('change',e=>{state.category=e.target.value;render()});
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='recipes')state.category='';setView(b.dataset.view)}));
  document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{state.currentId=b.dataset.open;state.view='detail';state.cookStep=0;render();window.scrollTo(0,0)}));
  document.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite)));
  document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;state.view='recipes';render()}));
  $('#openAI')?.addEventListener('click',()=>openAI($('#aiSource').value));
  $('#urlImport')?.addEventListener('click',importFromUrl);
  $('#jsonFile')?.addEventListener('change',async e=>{const f=e.target.files[0];if(f)$('#jsonArea').value=await f.text()});
  $('#importBtn')?.addEventListener('click',()=>importJson($('#jsonArea').value));
  $('#exportBtn')?.addEventListener('click',exportBackup);
  $('#startCook')?.addEventListener('click',()=>{state.view='cook';state.cookStep=0;requestWake();render();window.scrollTo(0,0)});
  $('#exitCook')?.addEventListener('click',()=>{releaseWake();state.view='detail';render()});
  $('#prevStep')?.addEventListener('click',()=>{state.cookStep=Math.max(0,state.cookStep-1);render();window.scrollTo(0,0)});
  $('#nextStep')?.addEventListener('click',()=>{const r=current();if(state.cookStep>=r.schritte.length-1){releaseWake();state.view='detail'}else state.cookStep++;render();window.scrollTo(0,0)});
  document.querySelectorAll('[data-ing]').forEach(c=>c.addEventListener('change',()=>toggleIngredient(+c.dataset.ing)));
  $('#detailFavorite')?.addEventListener('click',()=>toggleFavorite(current().id));
  $('#detailImageFile')?.addEventListener('change',e=>setImageFromFile(e.target.files[0]));
  $('#removeImage')?.addEventListener('click',async()=>{current().bild='';await saveRecipes();render();toast('Bild entfernt')});
  $('#deleteRecipe')?.addEventListener('click',deleteCurrent);
}

async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}}
async function openAI(source){const win=window.open('https://chatgpt.com/','_blank','noopener');const copied=await copyText(aiPrompt(source));toast(copied?'Auftrag kopiert – im neuen Chat einfügen':'Chat geöffnet – Auftrag konnte nicht kopiert werden',copied?'ok':'err');if(!win)toast('Pop-up blockiert. Erlaube Pop-ups für diese App.','err')}
function findRecipeJson(value){if(!value)return null;if(Array.isArray(value)){for(const v of value){const found=findRecipeJson(v);if(found)return found}}else if(typeof value==='object'){const type=value['@type'];if(type==='Recipe'||Array.isArray(type)&&type.includes('Recipe'))return value;if(value['@graph'])return findRecipeJson(value['@graph'])}return null}
function instructionText(item){if(typeof item==='string')return item;if(item?.text)return item.text;if(Array.isArray(item?.itemListElement))return item.itemListElement.map(instructionText).filter(Boolean).join(' ');return''}
function recipeFromSchema(r,url){let image=r.image||'';if(Array.isArray(image))image=image[0]||'';if(image&&typeof image==='object')image=image.url||image.contentUrl||'';let instructions=r.recipeInstructions||[];if(!Array.isArray(instructions))instructions=[instructions];instructions=instructions.flatMap(item=>item?.['@type']==='HowToSection'&&Array.isArray(item.itemListElement)?item.itemListElement:[item]).map((item,i)=>({titel:item?.name||`Schritt ${i+1}`,aktion:instructionText(item),startwert:'',zutaten:[],sinne:{},fertigWenn:'',warum:'',fehler:''})).filter(s=>s.aktion);let category=Array.isArray(r.recipeCategory)?r.recipeCategory[0]:r.recipeCategory;return normalizeRecipe({titel:r.name,kategorie:category||'Sonstiges',portionen:r.recipeYield||'',zeitGesamt:r.totalTime||r.cookTime||'',einleitung:r.description||'',bild:image,quelle:url,quelleName:new URL(url).hostname.replace(/^www\./,''),zutaten:(r.recipeIngredient||[]).map(x=>String(x)),schritte:instructions},false)}
async function importFromUrl(){const input=$('#urlInput');const url=input.value.trim();try{new URL(url)}catch(e){state.message='Bitte eine gültige URL eingeben.';state.messageType='err';render();return}state.message='URL wird geprüft …';state.messageType='ok';render();try{const response=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=await response.text();const doc=new DOMParser().parseFromString(html,'text/html');let schema=null;for(const script of doc.querySelectorAll('script[type="application/ld+json"]')){try{schema=findRecipeJson(JSON.parse(script.textContent));if(schema)break}catch(e){}}if(!schema)throw new Error('Keine strukturierten Rezeptdaten gefunden');const recipe=recipeFromSchema(schema,url);const errors=recipeValidationErrors(recipe);if(errors.length)throw new Error(errors.join(', '));await upsertRecipes([recipe]);state.message=`„${recipe.titel}“ wurde importiert. Das Bild bleibt eine externe URL und wurde nicht heruntergeladen.`;state.messageType='ok';render();toast('Rezept importiert')}catch(e){state.message='Die Website blockiert den direkten Import oder liefert unvollständige Daten. Ein neuer ChatGPT-Chat wurde geöffnet; der passende Auftrag ist kopiert.';state.messageType='err';render();openAI(url)}}
async function upsertRecipes(items){let added=0,updated=0;for(const d of items){const errors=recipeValidationErrors(d);if(errors.length)throw new Error(`„${d?.titel||d?.name||'Rezept'}“: ${errors.join(', ')}`);const nr=normalizeRecipe(d,Boolean(d.id));let idx=-1;if(nr.quelle)idx=state.recipes.findIndex(x=>x.quelle&&x.quelle===nr.quelle);if(idx<0)idx=state.recipes.findIndex(x=>norm(x.titel)===norm(nr.titel));if(idx>=0){nr.id=state.recipes[idx].id;state.recipes[idx]=nr;updated++}else{state.recipes.unshift(nr);added++}state.deletedPublishedIds=state.deletedPublishedIds.filter(id=>id!==nr.id)}await Promise.all([saveRecipes(),idbSet('deletedPublishedIds',state.deletedPublishedIds)]);return{added,updated}}
async function importJson(raw){let txt=(raw||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{const data=JSON.parse(txt);if(data&&Array.isArray(data.recipes)){for(const recipe of data.recipes){const errors=recipeValidationErrors(recipe);if(errors.length)throw new Error(`„${recipe?.titel||'Rezept'}“: ${errors.join(', ')}`)}state.recipes=data.recipes.map(r=>normalizeRecipe(r,true));state.favorites=Array.isArray(data.favorites)?data.favorites:[];state.deletedPublishedIds=Array.isArray(data.deletedPublishedIds)?data.deletedPublishedIds:[];await saveAll();await idbDelete('shopping');state.message='Backup vollständig wiederhergestellt.'}else{const result=await upsertRecipes(Array.isArray(data)?data:[data]);state.message=`Import abgeschlossen: ${result.added} neu, ${result.updated} aktualisiert.`}state.messageType='ok';render();toast(state.message)}catch(e){state.message=e.message||'Ungültiges JSON.';state.messageType='err';render()}}
function exportBackup(){const data={version:5,exportedAt:new Date().toISOString(),recipes:state.recipes,favorites:state.favorites,deletedPublishedIds:state.deletedPublishedIds};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kochbuch-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function toggleIngredient(i){const r=current();state.checkedIngredients[r.id]=state.checkedIngredients[r.id]||{};state.checkedIngredients[r.id][i]=!state.checkedIngredients[r.id][i];await idbSet('checkedIngredients',state.checkedIngredients);render()}
async function setImageFromFile(file){if(!file)return;try{current().bild=await compressImage(file);await saveRecipes();render();toast('Bild lokal in IndexedDB gespeichert')}catch(e){toast('Bild konnte nicht gespeichert werden','err')}}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const img=new Image();img.onerror=()=>resolve(reader.result);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.84))};img.src=reader.result};reader.readAsDataURL(file)})}
async function deleteCurrent(){const r=current();if(!r||!confirm(`„${r.titel}“ wirklich löschen?`))return;const published=DEFAULT_RECIPES.some(item=>item.id===r.id);if(published&&!state.deletedPublishedIds.includes(r.id))state.deletedPublishedIds.push(r.id);state.recipes=state.recipes.filter(x=>x.id!==r.id);state.favorites=state.favorites.filter(id=>id!==r.id);delete state.checkedIngredients[r.id];if(state.portionsByRecipe){delete state.portionsByRecipe[r.id];await idbSet('portionSelections',state.portionsByRecipe)}await Promise.all([saveRecipes(),idbSet('favorites',state.favorites),idbSet('checkedIngredients',state.checkedIngredients),idbSet('deletedPublishedIds',state.deletedPublishedIds)]);state.view='recipes';state.currentId=null;render();toast(published?'Rezept auf diesem Gerät dauerhaft ausgeblendet':'Rezept gelöscht')}
async function requestWake(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch(e){}}
async function releaseWake(){try{await wakeLock?.release()}catch(e){}wakeLock=null}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='recipes')state.category='';setView(b.dataset.view)}));
$('#themeBtn').addEventListener('click',toggleTheme);
window.addEventListener('keydown',e=>{if(state.view!=='cook')return;if(e.key==='ArrowRight')$('#nextStep')?.click();if(e.key==='ArrowLeft')$('#prevStep')?.click()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
init();